server:
  port: 8082
spring:
  cloud:
    config:
      server:
        git:
          default-label: eureka
          uri: https://github.com/Angelrjp/microservicios-tutorial
          search-paths: config-data
  application:
    name: config-service